Add users endpoint
jonasman/TeslaSwift pull request #131
Opened 2022-11-16 16:51 UTC by Urkman

Add the users endpoint to get the current authenticated user

2022-12-16 12:08 UTC, Urkman commented
added the remote boombox the PR

2023-05-14 11:25 UTC, jonasman commented on Sources/TeslaSwift/Model/Authentication.swift
> -import CryptoKit
Can you revert all changes here as the current Master branch already has the auth working correctly?

2023-05-14 11:25 UTC, jonasman commented on Sources/TeslaSwift/Model/User.swift
> +    }
this is not needed

2023-05-14 11:26 UTC, jonasman commented on Sources/TeslaSwift/TeslaSwift.swift
> +import Security
also here, all these auth changes can be reverted

2023-05-14 11:28 UTC, jonasman requested changes

2023-05-14 11:28 UTC, jonasman commented on Sources/TeslaSwift/TeslaSwift.swift
> +// MARK: - code to create code_verifier and challenge
all these stuff isnt needed anymore

2023-07-16 10:47 UTC, closed without merging